--Creating AuditLog Table
CREATE TABLE AuditLog
(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    ActionDate DATE
);


--Creating Trigger
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (
        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        ActionDate
    )
    VALUES
    (
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE
    );
END;
/


--Test
INSERT INTO Transactions
VALUES
(
    3,
    1,
    SYSDATE,
    500,
    'Deposit'
);

--Verify
SELECT *
FROM AuditLog;
